### ISSUE TITLE
Run observed command as non-root user

### ISSUE THREAD

**Issue by chapmanjacobd** [fabiensanglard/st#10]
It would be convenient to have the option to run the given command as a specific user

```
sudo -E ~/bin/ste python -m xklb.lb wt video.db -pa
EXEC: [ python -m xklb.lb wt video.db -pa]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/xk/github/xk/lb/xklb/lb.py", line 5, in <module>
    from xklb.dl_extract import dl_download
  File "/home/xk/github/xk/lb/xklb/dl_extract.py", line 4, in <module>
    from xklb import consts, db, gdl_backend, play_actions, player, tube_backend, usage, utils
  File "/home/xk/github/xk/lb/xklb/gdl_backend.py", line 5, in <module>
    import gallery_dl
ModuleNotFoundError: No module named 'gallery_dl'
```

**Comment by cwarden** [comment]
You can run it setuid root as of a4744cd37a88c1c2f32de2b7fbf77f773d7fd3ed.

**Comment by chapmanjacobd** [comment]
Yes, I can run it without sudo but I still get the same error as above

```
$ stat ~/bin/ste
File: /home/xk/bin/ste Size: 52952 Blocks: 104 IO Block: 4096 regular file
Device: 0,45 Inode: 47093160 Links: 1 Access: (4755/-rwsr-xr-x) Uid: ( 0/
root) Gid: ( 1000/ xk)
```

**Comment by fabiensanglard** [comment]
Try to pull and rebuild. It works for me.

```
# ./st ls
EXEC: [ ls]
a.out		   cmake-build-release	code	  exec-notify	 fillfill  index.html  make.sh	  screenshot.png  strlen
cmake-build-debug  CMakeLists.txt	debug.sh  exec-notify.c  hello	   LICENSE     README.md  st		  strleno
Num threads = 1
Num process = 1
Max PSS: 138,240 bytes
Walltime: 2ms - user-space: 1ms - kernel-space: 0ms
138┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┫█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
   ┃█████████████████████████████████████████████████████████████████████████████████████┃
0KB┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
   0ms                                                                                   2
```
